// Code generated by MockGen. DO NOT EDIT.
// Source: toggle_cache.go

// Package mocks is a generated GoMock package.
package mocks

import (
	x "github.com/feaggle/feaggle/pkg/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockToggleCache is a mock of ToggleCache interface
type MockToggleCache struct {
	ctrl     *gomock.Controller
	recorder *MockToggleCacheMockRecorder
}

// MockToggleCacheMockRecorder is the mock recorder for MockToggleCache
type MockToggleCacheMockRecorder struct {
	mock *MockToggleCache
}

// NewMockToggleCache creates a new mock instance
func NewMockToggleCache(ctrl *gomock.Controller) *MockToggleCache {
	mock := &MockToggleCache{ctrl: ctrl}
	mock.recorder = &MockToggleCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockToggleCache) EXPECT() *MockToggleCacheMockRecorder {
	return m.recorder
}

// Toggles mocks base method
func (m *MockToggleCache) Toggles() *x.Toggles {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Toggles")
	ret0, _ := ret[0].(*x.Toggles)
	return ret0
}

// Toggles indicates an expected call of Toggles
func (mr *MockToggleCacheMockRecorder) Toggles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Toggles", reflect.TypeOf((*MockToggleCache)(nil).Toggles))
}
