// Code generated by MockGen. DO NOT EDIT.
// Source: toggle_cache.go

// Package mocks is a generated GoMock package.
package mocks

import (
	x "github.com/feaggle/feaggle/pkg/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockToggleCache is a mock of ToggleCache interface
type MockToggleCache struct {
	ctrl     *gomock.Controller
	recorder *MockToggleCacheMockRecorder
}

// MockToggleCacheMockRecorder is the mock recorder for MockToggleCache
type MockToggleCacheMockRecorder struct {
	mock *MockToggleCache
}

// NewMockToggleCache creates a new mock instance
func NewMockToggleCache(ctrl *gomock.Controller) *MockToggleCache {
	mock := &MockToggleCache{ctrl: ctrl}
	mock.recorder = &MockToggleCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockToggleCache) EXPECT() *MockToggleCacheMockRecorder {
	return m.recorder
}

// Validate mocks base method
func (m *MockToggleCache) Validate() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Validate")
}

// Validate indicates an expected call of Validate
func (mr *MockToggleCacheMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockToggleCache)(nil).Validate))
}

// Cache mocks base method
func (m *MockToggleCache) Cache() *x.Toggles {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cache")
	ret0, _ := ret[0].(*x.Toggles)
	return ret0
}

// Cache indicates an expected call of Cache
func (mr *MockToggleCacheMockRecorder) Cache() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cache", reflect.TypeOf((*MockToggleCache)(nil).Cache))
}
